server:
  port: 9600

spring:
  application:
    name: fs01-3rd-1team-smart_apartment_management

  datasource:
    driver-class-name: ${JJLD_DRIVER}
    url: ${JJLD_URL}
    username: ${JJLD_USER}
    password: ${JJLD_PASS}
  sql:
    init:
      encoding: UTF-8
      mode: always

  jpa:
#    show-sql: true
    show-sql: false
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    defer-datasource-initialization: true

  mqtt:
    url: tcp://localhost:1883  # 브로커의 주소
    client-id: jjld-apartment-management2
    topic:
      # 발행(Publish)할 토픽
      command: jjld/command
      # 구독(Subscribe)할 토픽
      # 예시 - [본인 기능]: "jjld/[본인 기능]/#"
      # 토픽 등록 후 properties - MqttTopicProperties로 이동
      garden: "jjld/garden/#"
      elevator: "jjld/elevator/#"
      cargate: "jjld/cargate/#"

  springdoc:
    cache:
      disabled: true              # 캐시 사용 여부
    api-docs:
      path: /v3/api-docs
      groups:
        enabled: true
    swagger-ui:
      enabled: true               # Swagger UI 접근 경로 => http://localhost:9600/swagger-ui/index.html
      path: /swagger.html         # Swagger UI 추가 접근 경로 => http://localhost:8080/swagger.html
      tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
      operations-sorter: alpha    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}
  token-valid-in-second: 3600000
